### ISSUE TITLE
Atualizar link para `Ingressos`

### ISSUE THREAD

**Issue by camilamaia** [pythonbrasil/pythonbrasil-2020#11]
Atualizar link para `Ingressos` com o correto para a edição 2020.

![image](https://user-images.githubusercontent.com/2728804/92412805-a9044480-f123-11ea-92b2-8d9b9d9c310a.png)

**Comment by lucasrangels** [comment]
Issue resolvido nos commits 64a94b53530f3f83a5162b70f0a29bc3246b07d2 (header) e 611027ebdc48d55c7afe65b67bb1990fe310293e (main e footer)
