### ISSUE TITLE
Adicionar keynotes

### ISSUE THREAD

**Issue by camilamaia** [pythonbrasil/pythonbrasil-2020#19]
## Adicionar keynotes
![image](https://user-images.githubusercontent.com/2728804/92412685-35face00-f123-11ea-9d71-95eb80ebccab.png)

![image](https://user-images.githubusercontent.com/2728804/92412692-3d21dc00-f123-11ea-814b-6b189bf46d73.png)

**Comment by camilamaia** [comment]
@anadulce infos que precisamos de cada keynote:
- Nome
- Cargo
- Mini Bio
- Foto
- Linkedin
- GitHub

**Comment by anadulce** [comment]
Eita, vou ter que pedir mais uns dados então hahaha só tenho nome, minibio e foto

**Comment by rougeth** [comment]
Fechando a issue, obrigado pelo trabalho @camilamaia.
