### ISSUE TITLE
Link `Quero Patrocionar`

### ISSUE THREAD

**Issue by camilamaia** [pythonbrasil/pythonbrasil-2020#20]
Atualizar link `Quero Patrocionar`
![image](https://user-images.githubusercontent.com/2728804/92412846-d9e47980-f123-11ea-94e0-236442289fa5.png)

![image](https://user-images.githubusercontent.com/2728804/92412863-ee287680-f123-11ea-9ea3-c3c50389af85.png)

**Comment by camilamaia** [comment]
@anadulce temos um form para "quero patrocinar" atualmente? Senão, podemos esconder. Caso contrário, atualizamos.

**Comment by anadulce** [comment]
Temos os planos de patrocínio. Não serve? Lá tem o contato da organização.

**Comment by camilamaia** [comment]
@anadulce serve sim! Era exatamente isso que precisava :)

PR aberto já: https://github.com/pythonbrasil/pythonbrasil-2020/pull/22
