### ISSUE TITLE
Atualizar seção "O Evento"

### ISSUE THREAD

**Issue by camilamaia** [pythonbrasil/pythonbrasil-2020#6]
Atualizar seção "O Evento" com informações da Python Brasil 2020:

![image](https://user-images.githubusercontent.com/2728804/92412560-b5d46880-f122-11ea-8d84-3435c814912b.png)

**Comment by anadulce** [comment]
O Evento

A Python Brasil 2020 é a maior conferência sobre linguagem de programação Python do Brasil e da América Latina.

Feita pela comunidade para a comunidade, tem o objetivo de difundir a linguagem, disseminar conhecimento, promover a troca de experiências e manter a comunidade crescendo igualmente em público e impacto social.

Este ano, em caráter de exceção devido à pandemia de covid-19, a Python Brasil será realizada remotamente, organizada por um time distribuído no Brasil e no mundo, a fim de prosseguir com o seu objetivo de disseminar conhecimento e aproximar pessoas.

Serão sete dias de imersão, onde participantes poderão contribuir para projetos de software livre, participar de treinamentos e adquirir novos conhecimentos com outras pessoas da comunidade.

Seguindo o lema Pessoas > Tecnologia, gostamos de conhecer quem participa de nosso evento, por isso existem questões sobre como as pessoas se veem em nosso formulário de inscrições. Esses dados servirão como estatísticas sobre nosso público e também orientarão futuras aprimorações em nossas políticas de diversidade. Esperamos que você se sinta confortável em colaborar com nossa pesquisa.

Todas as pessoas que participam da Python Brasil devem concordar em seguir as orientações especificadas no Código de Conduta.

Se tiver qualquer dúvida não hesite em entrar em contato pelo e-mail eventos@python.org.br.

**Comment by camilamaia** [comment]
Closed by a59a638
