### ISSUE TITLE
Remove imagem/link de "Veja o Local" 

### ISSUE THREAD

**Issue by camilamaia** [pythonbrasil/pythonbrasil-2020#7]
Remove imagem/link de "Veja o Local" 

![image](https://user-images.githubusercontent.com/2728804/92412603-d3a1cd80-f122-11ea-9864-fb785a22817d.png)

**Comment by lucasrangels** [comment]
Issue resolvida pelo commit 92f5094d9c7ea0ec1315cacdcec9f6185284043f
